import React from "react";

export const metadata = {
  title: " Learning ||     Analytics Page",
  description: "Generated by create next app",
};
const Analytics = () => {
  throw new Error("Error Analytics");
  return (
    <div>
      <h2 className=" text-5xl text-green-700">Analytics Page</h2>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ab eaque
        placeat suscipit unde, temporibus in nobis dolorum quidem quasi
        molestias nesciunt excepturi deserunt, laudantium quo porro deleniti!
        Laboriosam ducimus laborum, repudiandae labore, ipsum aperiam a iste,
        voluptates cum reiciendis delectus tempore aliquid modi corrupti magni
        consectetur expedita nisi natus veniam unde atque officia nulla
        explicabo voluptas. Aperiam nemo, omnis aliquam quaerat explicabo
        voluptatum vero cumque ipsum repudiandae optio reiciendis dolores
        deleniti, tenetur, adipisci doloribus! Quas nam maxime molestias
        necessitatibus sapiente commodi earum. Harum temporibus, assumenda
        repellendus, voluptatibus dolores quidem nesciunt dignissimos laborum
        sapiente sed doloribus accusantium amet maiores ab. Incidunt
        necessitatibus, odit natus nulla quae blanditiis, ut doloremque ex
        delectus sequi aspernatur accusantium saepe, rem perferendis. Maiores
        eveniet libero neque, eum quos ducimus quis velit incidunt reprehenderit
        provident animi facilis quibusdam dignissimos quisquam temporibus esse
        laboriosam ipsum. Dignissimos a enim incidunt cupiditate dolor voluptate
        ducimus inventore iste porro quos ad quis corporis, ipsa distinctio
        temporibus hic alias recusandae laboriosam minus labore nostrum sit?
        Corrupti libero eos dolorum dolores, aliquam molestiae ipsum laudantium
        cumque? Repudiandae quas non, illo id maxime aut officia accusamus
        pariatur impedit molestias facere at libero perspiciatis earum
        perferendis beatae excepturi. Quo dignissimos saepe a, dolores placeat
        earum.
      </p>
    </div>
  );
};

export default Analytics;
