import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CustomLink from "./components/CustomLink";
import Error from "./error";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // throw  new  Error("Global") //Global not recommended (specially for API and Auth )
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" bg-gray-600 h-14  ">
          <ul className=" flex justify-center items-center gap-10  p-3">
            <li>
              <CustomLink path="/">Home</CustomLink>
            </li>
            <li>
              <CustomLink path="/dashboard/analytics">Analytics</CustomLink>
            </li>
            <li>
              <CustomLink path="/dashboard/settings"> Settings</CustomLink>
            </li>
            <li>
              <CustomLink path="/heavy"> Heavy</CustomLink>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
